---
- hosts: asa
  gather_facts: no
  connection: local

  vars:
    limit_to: "*"

  roles:
    - { role: test_asa_command, when: "limit_to in ['*', 'asa_command']" }
    - { role: test_asa_config, when: "limit_to in ['*', 'asa_config']" }
