---
- hosts: dellos6
  gather_facts: no
  connection: local

  vars:
    limit_to: "*"
    test_items: ""

  roles:
    - { role: test_dellos6_command, when: "limit_to in ['*', 'dellos6_command']" }
    - { role: test_dellos6_config, when: "limit_to in ['*', 'dellos6_config']" }
    - { role: test_dellos6_template, when: "limit_to in ['*', 'dellos6_template']" }
    - { role: test_dellos6_facts, when: "limit_to in ['*', 'dellos6_facts']" }
