---
- hosts: iosxr
  gather_facts: no
  connection: local

  vars:
    limit_to: "*"
    debug: false

  roles:
    - { role: test_iosxr_command, when: "limit_to in ['*', 'iosxr_command']" }
    - { role: test_iosxr_config, when: "limit_to in ['*', 'iosxr_config']" }
    - { role: test_iosxr_facts, when: "limit_to in ['*', 'iosxr_facts']" }
    - { role: test_iosxr_template, when: "limit_to in ['*', 'iosxr_template']" }


